### ISSUE TITLE
Looking forward to the code

### ISSUE THREAD

**Issue by KaneKun** [sungonce/CVNet#1]
Hello, thank you so much for the amazing work! It inspires me a lot.

May I ask if there is a (rough) date for the code to be released? I am looking forward to this masterpiece :)

**Comment by izhangcd** [comment]
I want to ask the same thing!

**Comment by sungonce** [comment]
We are currently preparing to upload the code and will update it near the conference period.

**Comment by jellchou** [comment]
So an amazing work compared with state-of-the-work methods. Can not wait to read the code line by line！

**Comment by luffytomato** [comment]
Can no wait to read the code, please share asap.

**Comment by Vincentqyw** [comment]
Great work! Any schedule to release the code？

**Comment by chensiqin** [comment]
Thank you for your good work! Any plan to release the training code?

**Comment by sungonce** [comment]
@jellchou @luffytomato @Vincentqyw We uploaded the code.
@chensiqin We do not have a plan to release the training code because of the conflicts with the intellectual property of the company.
