### ISSUE TITLE
Regarding evaluation results for GLD-v2

### ISSUE THREAD

**Issue by SunghwanHong** [sungonce/CVNet#3]
Hi, 
Thanks for releasing the codes for this amazing work. 
I just quickly took a look at the entire codes, and it seems that the codes for GLD-v2 is not there.
Is there any plan to release the pretrained weights and codes for GLD-v2 dataset?

**Comment by sungonce** [comment]
Our code does not require any additional weights for the GLDv2-retrieval task. Just use the provided weight as it is.
The GLDv2-retrieval test can be done by referring to the following [link](https://github.com/cvdfoundation/google-landmark), there are no plans to provide additional test code in this repository.
